const KEY='p1-client-profile-v1';
const LINK_DEFS=[['SharePoint','sp','SP'],['Client Technical Docs','ctd','TD'],['ClickUp Client Folder','cu','CU'],['GitHub Repository','gh','GH'],['GitHub Pages / Live Doc','live','↗'],['Passportal','pp','PP'],['ConnectWise Company','cw','CW'],['Proposal / Agreement','prop','PA'],['Discovery / Meeting Notes','notes','MN']];
function q(s,r=document){return r.querySelector(s)}function qa(s,r=document){return [...r.querySelectorAll(s)]}
function renderLinks(){q('#quicklinks').innerHTML=LINK_DEFS.map(([name,k,ic])=>`<div class="linkbox"><div class="linktop"><span class="ico">${ic}</span><strong>${name}</strong></div><input type="url" data-f="lk-${k}" placeholder="paste approved link"><a class="openlink off" data-link="lk-${k}" target="_blank" rel="noopener">Open resource →</a></div>`).join('')}
function fieldRoot(el){let p=el.closest('[data-section]');return p?p.querySelector('.cardbody'):null}
function applyNA(){qa('[data-section]').forEach(s=>{let c=s.querySelector('input[data-f^="na-"]');s.classList.toggle('na-on',!!c?.checked)})}
function allFields(){return qa('[data-f]')}
function save(){const d={};allFields().forEach(el=>{d[el.dataset.f]=el.type==='checkbox'?el.checked:el.value});localStorage.setItem(KEY,JSON.stringify(d));updateDerived()}
function restore(){let d={};try{d=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{};allFields().forEach(el=>{if(Object.prototype.hasOwnProperty.call(d,el.dataset.f)){if(el.type==='checkbox')el.checked=!!d[el.dataset.f];else el.value=d[el.dataset.f]}});applyNA();updateDerived()}
function makeId(){return Math.random().toString(36).slice(2,10)}
function addRow(kind){const body=q(`[data-rows="${kind}"]`),last=body.lastElementChild,clone=last.cloneNode(true),id='r'+makeId();qa('[data-f]',clone).forEach(el=>{el.dataset.f=el.dataset.f.replace(/-r[^-]*$/,'-'+id);if(el.type==='checkbox')el.checked=false;else el.value=''});body.appendChild(clone);save()}
function fmtDate(v){if(!v)return'—';let d=new Date(v+(v.length===10?'T12:00:00':''));return isNaN(d)?'—':d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
function updateDerived(){const v=k=>q(`[data-f="${k}"]`)?.value||'';qa('[data-link]').forEach(a=>{let url=v(a.dataset.link);a.href=url||'#';a.classList.toggle('off',!url)});let rows=qa('[data-rows="projects"] tr');let open=rows.filter(r=>{let st=q('select[data-f^="pr-status"]',r)?.value;let name=q('input[data-f^="pr-name"]',r)?.value;return name&&st!=='Complete'});q('#m-projects').textContent=open.length;let dues=open.map(r=>q('input[data-f^="pr-due"]',r)?.value).filter(Boolean).sort();q('#m-due').textContent=dues.length?fmtDate(dues[0]).replace(/, \d{4}/,''):'—';let mt=v('mt-next');q('#m-meeting').textContent=mt?new Date(mt).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'—';q('#m-meeting-type').textContent=v('mt-type')||'not scheduled';let core=['cp-name','cp-type','cp-status','cp-health','cp-owner','cp-tech-owner','lk-sp','lk-cu','mt-next','ac-internal'];let done=core.filter(k=>v(k)).length;q('#m-ready').textContent=Math.round(done/core.length*100)+'%';q('#s-owner').textContent=v('cp-owner')||'—';q('#s-type').textContent=v('cp-type')||'—';q('#s-health').textContent=v('cp-health')||'—';q('#s-follow').textContent=fmtDate(v('mt-follow'))}
function labels(){const out={};allFields().forEach(el=>{let f=el.closest('.field'),lab=f?.querySelector('label')?.textContent.trim();if(!lab&&el.closest('td'))lab=el.closest('table')?.querySelectorAll('th')[el.closest('td').cellIndex]?.textContent.trim();out[el.dataset.f]=lab||el.getAttribute('aria-label')||el.dataset.f});return out}
function openFill(){const L=labels();const lines=allFields().filter(el=>!el.dataset.f.startsWith('na-')).map(el=>`- ${L[el.dataset.f]}\n  key: ${el.dataset.f}\n  guidance: ${el.placeholder||'Use source-supported information only.'}`);q('#fillText').value=lines.join('\n\n');q('#fillModal').classList.add('on')}
function copyFill(){const pre='Fill this Plus 1 Client Profile using only the supplied source material. Never invent. For unknown or unsupported values, use [PENDING: reason]. Return one flat JSON object only, with the exact keys below. Do not include passwords, tokens, API keys, or secrets.\n\n';navigator.clipboard.writeText(pre+q('#fillText').value)}
function openImport(){q('#importModal').classList.add('on')}
function closeModals(){qa('.modal').forEach(m=>m.classList.remove('on'))}
function importAnswers(){let o;try{o=JSON.parse(q('#importText').value)}catch(e){q('#importResult').textContent='Invalid JSON: '+e.message;return}let matched=0,unknown=[];for(const[k,val]of Object.entries(o)){let el=q(`[data-f="${CSS.escape(k)}"]`);if(!el){unknown.push(k);continue}if(el.type==='checkbox')el.checked=!!val;else el.value=val==null?'':String(val);matched++}save();restore();q('#importResult').textContent=`Imported ${matched} fields.${unknown.length?' Unknown keys: '+unknown.join(', '):''}`}
function copySummary(){const v=k=>q(`[data-f="${k}"]`)?.value||'—';let projects=qa('[data-rows="projects"] tr').map(r=>{let g=p=>q(`[data-f^="${p}"]`,r)?.value||'';return g('pr-name')?`• ${g('pr-name')} — ${g('pr-status')||'status pending'} — due ${fmtDate(g('pr-due'))}`:''}).filter(Boolean).join('\n')||'• No open projects listed';let text=`${v('cp-name')} — Client Profile\nType: ${v('cp-type')} | Status: ${v('cp-status')} | Health: ${v('cp-health')}\nAccount owner: ${v('cp-owner')} | Technical lead: ${v('cp-tech-owner')}\n\nOpen projects\n${projects}\n\nNext meeting: ${v('mt-next')} — ${v('mt-type')}\nNext internal action: ${v('ac-internal')} (${v('ac-internal-owner')}, due ${fmtDate(v('ac-internal-due'))})\nNext client action: ${v('ac-client')} (${v('ac-client-owner')}, due ${fmtDate(v('ac-client-due'))})\n\nPriorities / risks\n${v('px-priorities')}\n${v('px-risks')}`;navigator.clipboard.writeText(text)}
document.addEventListener('input',e=>{if(e.target.matches('[data-f]')){applyNA();save()}});document.addEventListener('change',e=>{if(e.target.matches('[data-f]')){applyNA();save()}});document.addEventListener('click',e=>{let a=e.target.closest('[data-add]');if(a)addRow(a.dataset.add);let t=e.target.closest('.trash');if(t){let body=t.closest('tbody');if(body.children.length===1){qa('input,select,textarea',t.closest('tr')).forEach(x=>x.value='')}else t.closest('tr').remove();save()}});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});renderLinks();restore();